import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { waitForPageReady, loginAsAdmin, setDarkMode } from './helpers';

// ============================================================================
// Targeted Screenshot Capture
// ============================================================================
// Captures screenshots of specific routes that were affected by code changes.
// Routes are read from affected-routes.json (generated by screenshot-affected.ts)
//
// Usage:
//   npm run screenshot:affected  (runs this automatically)
//   npx playwright test e2e/targeted-screenshots.spec.ts --project=e2e-bypass

interface AffectedRoutesConfig {
  routes: string[];
  branch: string;
  screenshotDir: string;
  generatedAt: string;
}

// Load affected routes from JSON file
function loadAffectedRoutes(): AffectedRoutesConfig | null {
  const configPath = path.join(process.cwd(), 'affected-routes.json');

  if (!fs.existsSync(configPath)) {
    console.log('No affected-routes.json found. Run: npm run screenshot:affected');
    return null;
  }

  return JSON.parse(fs.readFileSync(configPath, 'utf-8'));
}

// Convert route to safe filename
function routeToFilename(route: string): string {
  if (route === '/') return 'home';
  return route.replace(/\//g, '-').replace(/^-/, '').replace(/\[([^\]]+)\]/g, '$1');
}

// Check if route requires admin auth
function requiresAuth(route: string): boolean {
  return route.startsWith('/admin') || route.startsWith('/dashboard');
}

// Check if route is dynamic (has [slug] or similar)
function isDynamicRoute(route: string): boolean {
  return route.includes('[');
}

const config = loadAffectedRoutes();

// Skip all tests if no config
test.describe('Targeted Screenshots', () => {
  test.skip(!config, 'No affected routes to screenshot');

  if (!config) return;

  const { routes, screenshotDir } = config;
  const screenshotPath = path.join(process.cwd(), 'public', 'screenshots', screenshotDir);

  // Ensure screenshot directory exists
  test.beforeAll(() => {
    if (!fs.existsSync(screenshotPath)) {
      fs.mkdirSync(screenshotPath, { recursive: true });
    }
  });

  // Filter out dynamic routes for now (would need test data)
  const staticRoutes = routes.filter((r) => !isDynamicRoute(r));

  // Desktop Light Mode
  test.describe('Desktop - Light Mode', () => {
    for (const route of staticRoutes) {
      test(`${route} - desktop light`, async ({ page }) => {
        // Login if needed
        if (requiresAuth(route)) {
          await loginAsAdmin(page);
        }

        // Navigate and wait
        await page.goto(route);
        await waitForPageReady(page);

        // Capture screenshot
        const filename = `${routeToFilename(route)}-desktop-light.png`;
        await page.screenshot({
          path: path.join(screenshotPath, filename),
          fullPage: true,
        });
      });
    }
  });

  // Desktop Dark Mode
  test.describe('Desktop - Dark Mode', () => {
    for (const route of staticRoutes) {
      test(`${route} - desktop dark`, async ({ page }) => {
        // Login if needed
        if (requiresAuth(route)) {
          await loginAsAdmin(page);
        }

        // Navigate and wait
        await page.goto(route);
        // Enable dark mode via class (Tailwind uses darkMode: 'class')
        await setDarkMode(page);
        await waitForPageReady(page);

        // Capture screenshot
        const filename = `${routeToFilename(route)}-desktop-dark.png`;
        await page.screenshot({
          path: path.join(screenshotPath, filename),
          fullPage: true,
        });
      });
    }
  });

  // Mobile Light Mode
  test.describe('Mobile - Light Mode', () => {
    test.use({ viewport: { width: 390, height: 844 } });

    for (const route of staticRoutes) {
      test(`${route} - mobile light`, async ({ page }) => {
        // Login if needed
        if (requiresAuth(route)) {
          await loginAsAdmin(page);
        }

        // Navigate and wait
        await page.goto(route);
        await waitForPageReady(page);

        // Capture screenshot
        const filename = `${routeToFilename(route)}-mobile-light.png`;
        await page.screenshot({
          path: path.join(screenshotPath, filename),
          fullPage: true,
        });
      });
    }
  });

  // Mobile Dark Mode
  test.describe('Mobile - Dark Mode', () => {
    test.use({ viewport: { width: 390, height: 844 } });

    for (const route of staticRoutes) {
      test(`${route} - mobile dark`, async ({ page }) => {
        // Login if needed
        if (requiresAuth(route)) {
          await loginAsAdmin(page);
        }

        // Navigate and wait
        await page.goto(route);
        // Enable dark mode via class (Tailwind uses darkMode: 'class')
        await setDarkMode(page);
        await waitForPageReady(page);

        // Capture screenshot
        const filename = `${routeToFilename(route)}-mobile-dark.png`;
        await page.screenshot({
          path: path.join(screenshotPath, filename),
          fullPage: true,
        });
      });
    }
  });
});
