import type { BlogPost } from '@/lib/blog-types';

type RetainedArticleCopy = Pick<
  BlogPost,
  'title' | 'excerpt' | 'content' | 'meta_title' | 'meta_description'
>;

const codeBlock = (language: string, lines: string[]) => [
  `\`\`\`${language}`,
  ...lines,
  '\`\`\`',
].join('\n');

const retainedArticleCopy: Record<string, RetainedArticleCopy> = {
  'ai-context-budget-tips': {
    title: 'A Smaller AI Brief Works Better',
    excerpt: 'We removed repeated instructions from our AI coding setup. These practical edits leave more room for useful context.',
    meta_title: 'A Smaller AI Brief Works Better',
    meta_description: 'Practical ways to remove repeated instructions and leave more room for useful AI coding context.',
    content: [
      'Our coding assistant read the same product rule eight times before answering one question.',
      'The duplicate text wasted context. It also made the brief harder to maintain.',
      '## Context Is a Budget',
      'Every AI tool has a context window. It can hold only so much text at once.',
      'Instructions, code, conversation history, and reasoning share that space.',
      'Repeated instructions leave less room for the current task.',
      'Think of context like a desk. Eight copies of one memo leave little room to work.',
      '## What We Found',
      'We reviewed 31 instruction files. They contained about 4,850 lines of setup guidance.',
      'The same color system appeared in three files.',
      'The same product rule appeared in eight places.',
      'A 55-line changelog repeated information already available through `git log`.',
      'Several files repeated the same test instructions.',
      'We had added guidance over several months. We did not check for overlap.',
      '## Five Fixes',
      '**Find duplicates.** Search for each important rule across the instruction files.',
      'If a rule appears several times, choose one home for it.',
      '**Layer instructions.** Put broad rules at the top. Put local rules near the code they govern.',
      '**Point instead of repeating.** Link to the source of truth from other files.',
      'A short pointer keeps the rule easy to find. It also prevents drift.',
      '**Delete tracked information.** Git already records changes. We removed the duplicate changelog.',
      '**Measure the result.** We removed about 800 lines. That freed roughly 7,200 tokens per session.',
      '## Why This Matters',
      'Context cleanup is not a one-time task. Every new instruction has a cost.',
      'Good editors keep the brief focused. They leave room for the work that matters now.',
      'The same model can work better with a clearer brief.',
      '## Check Your Setup',
      'Try this five-minute review:',
      '1. Count your instruction files and their total lines.',
      '2. Search for three key terms across those files.',
      '3. Remove information your tools already track.',
      'The assistant did not get smarter. We stopped making it read the same thing eight times.',
    ].join('\n\n'),
  },
  'loading-tricks-feel-instant': {
    title: '4 Loading Tricks That Make a Site Feel Faster',
    excerpt: 'Four techniques can make loading feel smoother. They help while iframes and heavy content finish loading.',
    meta_title: '4 Loading Tricks That Make a Site Feel Faster',
    meta_description: 'Four practical techniques for smoother loading while iframes and heavy content finish loading.',
    content: [
      'Web performance has a measured side and an experienced side.',
      'A page can load quickly and still feel rough. A slower page can feel calm and deliberate.',
      'We used these patterns for device mockups that load our site inside iframes.',
      'The patterns improve the transition. They do not change the actual load time.',
      '## 1. Snapshot Placeholders',
      '**The problem:** A spinner left the device frame looking unfinished for one to three seconds.',
      '**The trick:** Show a saved image while the live iframe loads behind it.',
      codeBlock('tsx', [
        '{/* Static placeholder; renders instantly */}',
        '{placeholderSrc && (',
        '  <img',
        '    src={placeholderSrc}',
        '    alt=""',
        '    className="absolute inset-0 w-full h-full object-cover',
        '               transition-opacity duration-500"',
        '    style={{ opacity: iframeLoaded ? 0 : 1 }}',
        '  />',
        ')}',
        '',
        '{/* Real iframe; loads in background */}',
        '<iframe',
        '  src={url}',
        '  onLoad={() => setIframeLoaded(true)}',
        '  className="w-full h-full"',
        '/>',
      ]),
      'The image appears first. The iframe loads without leaving an empty frame.',
      'When the iframe loads, the image fades away.',
      'The placeholder only needs to prevent an empty layout. It does not need to be perfect.',
      '## 2. Crossfade When Ready',
      '**The problem:** Hiding the device created blank space before the content appeared.',
      '**The trick:** Show the placeholder immediately. Fade into the live content later.',
      codeBlock('tsx', [
        '<motion.div',
        '  initial={{ opacity: 0.9 }}',
        '  animate={{ opacity: 1 }}',
        '  transition={{ duration: 0.5 }}',
        '>',
        '  {/* Device with placeholder already visible */}',
        '</motion.div>',
      ]),
      'The first frame already contains useful visual content.',
      'The live page replaces it with a quiet opacity change.',
      '## 3. Use Declarative Animation',
      '**The problem:** An imperative callback chain can leave a device hidden forever.',
      '**The trick:** Start the animation on mount. Do not depend on iframe timing.',
      codeBlock('tsx', [
        '// Imperative (fragile):',
        'const controls = useAnimationControls();',
        'const handleLoad = () => controls.start({ opacity: 1 });',
        '// If onLoad never fires... the device never appears.',
        '',
        '// Declarative (resilient):',
        '<motion.div',
        '  initial={{ opacity: 0.6, y: 10 }}',
        '  animate={{ opacity: 1, y: 0 }}',
        '  transition={{ duration: 0.8, delay: 0.2 }}',
        '>',
      ]),
      'The animation runs even when the iframe is slow.',
      'A fallback timeout can still reveal the device after eight seconds.',
      '## 4. Hide Overflow at the Container',
      '**The problem:** Iframes can flash a horizontal scrollbar while they settle.',
      '**The trick:** Hide overflow on the container around the device group.',
      codeBlock('css', [
        '/* On the hero preview wrapper */',
        '.hero-preview-container {',
        '  overflow: hidden;',
        '}',
      ]),
      'The container catches the flash without clipping device shadows or controls.',
      '## Put the Patterns Together',
      '1. Snapshot placeholder: show visual content at once.',
      '2. Crossfade: move quietly into the live state.',
      '3. Declarative animation: appear regardless of load timing.',
      '4. Container overflow: prevent visual artifacts.',
      '## The Broader Lesson',
      'These patterns do not make the iframe load faster.',
      'They make each loading state look intentional.',
      'Show something useful immediately. Upgrade it quietly. Avoid incomplete flashes.',
    ].join('\n\n'),
  },
  'rewriting-copy-plain-language': {
    title: 'Plain-Language Copy Helps People Understand Technical Work',
    excerpt: 'We rewrote technical portfolio copy for business readers. The work stayed accurate while the outcomes became easier to see.',
    meta_title: 'Plain-Language Copy Helps People Understand Technical Work',
    meta_description: 'How to translate technical portfolio language into clear outcomes without losing accuracy.',
    content: [
      'This sentence stopped me while I reviewed our portfolio:',
      '*"Production-grade reliability: circuit breaker, retry logic, request deduplication."*',
      'It was accurate. It was not clear to a business reader.',
      'The site sounded like a resume for engineers. It needed to speak to the people who choose the work.',
      '## The Jargon Trap',
      'Technical teams often describe how they built something.',
      'Visitors usually need to know what it does for them.',
      'A term can be precise and still fail to communicate.',
      'For example, `RAG` and `pgvector` explain implementation. They do not explain the customer-facing result.',
      '## What We Changed',
      'We rewrote the portfolio, contact page, and about page.',
      'The code change was small. The reader-facing change was clearer.',
      '**Before:** *"Production e-commerce platform serving real customers. Built from scratch with Next.js 14, TypeScript, and a microservices architecture connecting Medusa, Supabase, Stripe, and Redis."*.',
      '**After:** *"Online store and business platform built from scratch. Handles payments, bookings, email campaigns, and customer accounts in one place."*.',
      'The second version describes the work in terms of what it does.',
      'A technical reader can still find the stack in separate badges or notes.',
      '## Rewrite the Impact Bullets',
      '**Before:** *"1,300+ commits in under 3 months of intense development"*.',
      '**After:** *"Built from zero to production in under 3 months"*.',
      '**Before:** *"Production-grade reliability: circuit breaker, retry logic, request deduplication"*.',
      '**After:** *"Built-in safeguards help the system recover when something goes wrong"*.',
      '**Before:** *"AI chatbot with RAG (pgvector + OpenAI) answering customer questions from indexed site content"*.',
      '**After:** *"Chatbot that uses website content to answer customer questions"*.',
      'The translations keep the underlying ideas intact.',
      'They give a reader a reason to care before naming the implementation.',
      '## Three Rules',
      '**Describe outcomes, not ingredients.** People order cake. They do not order flour arranged in layers.',
      '**Replace terms that need a parenthetical.** Use the result when the pattern name adds no value.',
      '**Keep technical details available.** Put stack names in a separate place for readers who want them.',
      '## Fix the Heading Order',
      'Clear headings help people scan a page.',
      'They also help screen-reader users build a page outline.',
      'We fixed pages that jumped from H1 to H3.',
      'The component now uses H2 for project titles and H3 for subtitles.',
      '## The Takeaway',
      'You do not need to hide impressive technical work.',
      'You do need to translate it.',
      'Describe the outcome first. Keep the recipe available for people who need it.',
    ].join('\n\n'),
  },
};

export function getRetainedArticleCopy(slug: string): RetainedArticleCopy | null {
  return retainedArticleCopy[slug] || null;
}

export const RETAINED_ARTICLE_COPY = retainedArticleCopy;
