#!/bin/bash

# ============================================================================
# Full-Stack Template Setup Script
# ============================================================================
# What does this script do?
# Initializes a new project from this template by filling out your custom
# environment settings. Think of it as a form that sets up your restaurant -
# naming it, getting your suppliers' contact info, setting your hours, etc.
#
# When to run it?
# Once, when you first start a new project from this template
#
# What it will ask:
# - Project name (appears in browser tabs, emails, etc)
# - Domain name (where your app will live)
# - Supabase URL and keys (your database)
#
# What it will generate:
# - .env.local file with your custom settings
# - Secrets for secure session management

set -e  # Exit if any command fails (safety first)

echo "======================================================================="
echo "Full-Stack Template Setup"
echo "======================================================================="
echo ""
echo "This script will help you initialize a new project from this template."
echo "You'll be asked a few questions, then your .env.local file will be created."
echo ""

# ============================================================================
# Collect User Input
# ============================================================================

# Project name
echo "What's the name of your project?"
echo "Example: My Awesome App"
read -p "> " project_name

# Domain name
echo ""
echo "What domain will this project run on?"
echo "Example: myapp.com (or localhost for local development)"
read -p "> " domain_name

# Supabase URL
echo ""
echo "Now we need your Supabase credentials."
echo "You can find these at: https://app.supabase.com"
echo "Go to your project → Settings → API"
echo ""
echo "Enter your Supabase Project URL:"
echo "Example: https://myproject.supabase.co"
read -p "> " supabase_url

# Supabase anon key
echo ""
echo "Enter your Supabase Anon Key (the public key):"
read -p "> " supabase_anon_key

# Supabase service role key
echo ""
echo "Enter your Supabase Service Role Key (keep this secret!):"
read -s -p "> " supabase_service_role_key
echo ""

# ============================================================================
# Generate Secrets
# ============================================================================
# Create random strings for secure session management
# These need to be unique and unguessable

echo ""
echo "Generating secure secrets..."

# Generate session secret (32 random bytes, base64 encoded)
session_secret=$(openssl rand -base64 32)

# Generate a timestamp for uniqueness
timestamp=$(date +%s)

# ============================================================================
# Create .env.local File
# ============================================================================
# Fill in the template with user's custom values

cat > .env.local <<EOF
# Full-Stack Template Configuration
# Generated by setup.sh on $(date)

# ============================================================================
# General Settings
# ============================================================================
NODE_ENV=development
APP_URL=http://localhost:3000
APP_NAME=$project_name

# ============================================================================
# Supabase Configuration
# ============================================================================
NEXT_PUBLIC_SUPABASE_URL=$supabase_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$supabase_anon_key
SUPABASE_SERVICE_ROLE_KEY=$supabase_service_role_key

# ============================================================================
# Redis Configuration
# ============================================================================
REDIS_URL=redis://redis:6379

# ============================================================================
# Session & Security
# ============================================================================
SESSION_SECRET=$session_secret
SESSION_MAX_AGE=2592000
EOF

echo ""
echo "======================================================================="
echo "✓ Setup Complete!"
echo "======================================================================="
echo ""
echo "Your .env.local file has been created with your settings."
echo ""
echo "Next steps:"
echo "1. Make sure Docker Desktop is running"
echo "2. Run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up"
echo "3. Open your browser to: http://localhost"
echo ""
echo "Happy building! 🚀"
echo ""
