-- ============================================================================
-- Migration: Create Quote with Project Update Transaction
-- ============================================================================
-- Purpose: Atomically create a quote and update linked project status
-- Why: Prevent orphaned data if quote creation succeeds but project update fails
-- Impact: Ensures data consistency between quotes and projects tables

CREATE OR REPLACE FUNCTION public.create_quote_with_project_update(
  p_customer_name TEXT,
  p_customer_email TEXT,
  p_project_id UUID,
  p_total_amount INTEGER,
  p_deposit_amount INTEGER,
  p_expires_at TIMESTAMPTZ,
  p_notes TEXT
)
RETURNS TABLE (
  id UUID,
  reference_number TEXT,
  customer_name TEXT,
  customer_email TEXT,
  project_id UUID,
  total_amount INTEGER,
  deposit_amount INTEGER,
  status TEXT,
  expires_at TIMESTAMPTZ,
  notes TEXT,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_quote_id UUID;
  v_reference_number TEXT;
BEGIN
  -- ========================================================================
  -- Validation: Verify project exists
  -- ========================================================================
  IF NOT EXISTS (SELECT 1 FROM public.projects WHERE public.projects.id = p_project_id) THEN
    RAISE EXCEPTION 'Project with ID % does not exist', p_project_id;
  END IF;

  -- ========================================================================
  -- Step 1: Create the quote (reference_number auto-generated by trigger)
  -- ========================================================================
  INSERT INTO public.quotes (
    customer_name,
    customer_email,
    project_id,
    total_amount,
    deposit_amount,
    status,
    expires_at,
    notes
  )
  VALUES (
    p_customer_name,
    p_customer_email,
    p_project_id,
    p_total_amount,
    p_deposit_amount,
    'draft',
    p_expires_at,
    p_notes
  )
  RETURNING quotes.id, quotes.reference_number INTO v_quote_id, v_reference_number;

  -- ========================================================================
  -- Step 2: Update project status to 'quoted'
  -- ========================================================================
  UPDATE public.projects
  SET status = 'quoted',
      updated_at = NOW()
  WHERE public.projects.id = p_project_id;

  -- ========================================================================
  -- Return the created quote
  -- ========================================================================
  RETURN QUERY
  SELECT
    q.id,
    q.reference_number,
    q.customer_name,
    q.customer_email,
    q.project_id,
    q.total_amount,
    q.deposit_amount,
    q.status,
    q.expires_at,
    q.notes,
    q.created_at,
    q.updated_at
  FROM public.quotes q
  WHERE q.id = v_quote_id;

  -- Transaction automatically commits if no exception raised
  -- Automatically rolls back if any step fails
END;
$$;

-- Add comment for documentation
COMMENT ON FUNCTION public.create_quote_with_project_update IS 'Atomically creates a quote and updates the linked project status to "quoted". Ensures data consistency by wrapping both operations in a transaction.';

-- Grant execute permission
GRANT EXECUTE ON FUNCTION public.create_quote_with_project_update TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_quote_with_project_update TO service_role;
