#!/usr/bin/env tsx
/**
 * Generate Content Manifest Script
 *
 * This script scans the /content directory and generates a TypeScript manifest file
 * that maps routes to their editable content slugs.
 *
 * Usage: npx tsx scripts/generate-content-manifest.ts
 *
 * Output: lib/generated/content-manifest.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import {
  discoverContentFiles,
  generateRouteManifest,
  type ContentManifest,
} from '../lib/content-discovery';

// ============================================================================
// Configuration
// ============================================================================

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..');
const CONTENT_DIR = path.join(PROJECT_ROOT, 'content');
const OUTPUT_DIR = path.join(PROJECT_ROOT, 'lib', 'generated');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'content-manifest.ts');

// ============================================================================
// Main Script
// ============================================================================

function main(): void {
  console.log('📁 Scanning content directory:', CONTENT_DIR);

  // Check if content directory exists
  if (!fs.existsSync(CONTENT_DIR)) {
    console.log('⚠️  Content directory does not exist, creating empty manifest...');
    writeManifest({});
    return;
  }

  // Discover content files
  const contentFiles = discoverContentFiles(CONTENT_DIR);
  console.log(`📄 Found ${contentFiles.length} content files:`);
  contentFiles.forEach((file) => console.log(`   - ${file}`));

  // Generate route manifest
  const manifest = generateRouteManifest(contentFiles);
  console.log(`🗺️  Generated ${Object.keys(manifest).length} route mappings`);

  // Write manifest file
  writeManifest(manifest);
  console.log('✅ Content manifest generated successfully!');
}

function writeManifest(manifest: ContentManifest): void {
  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Generate TypeScript content
  const content = `// ============================================================================
// Auto-generated Content Manifest
// ============================================================================
// DO NOT EDIT MANUALLY - This file is generated by scripts/generate-content-manifest.ts
// Run \`npm run generate:manifest\` to regenerate
//
// Generated at: ${new Date().toISOString()}

import type { ContentManifest } from '../content-discovery';

/**
 * Maps routes to their editable content slugs.
 * Auto-discovered from /content/*.json files.
 */
export const contentManifest: ContentManifest = ${JSON.stringify(manifest, null, 2)};

/**
 * All editable routes discovered from content files.
 */
export const editableRoutes = Object.keys(contentManifest);

/**
 * Check if a route is editable (has content file).
 */
export function isRouteEditable(route: string): boolean {
  const normalizedRoute = route === '/' ? '/' : route.replace(/\\/$/, '');
  return normalizedRoute in contentManifest;
}

/**
 * Get the content slug for a route.
 */
export function getSlugForRoute(route: string): string | null {
  const normalizedRoute = route === '/' ? '/' : route.replace(/\\/$/, '');
  return contentManifest[normalizedRoute] ?? null;
}
`;

  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
  console.log(`📝 Written manifest to: ${OUTPUT_FILE}`);
}

// Run the script
main();
