'use client';

import { useState, useMemo } from 'react';
import PageHeader from '@/components/PageHeader';
import Card from '@/components/Card';
import { headingColors, formInputColors } from '@/lib/colors';
import changelogData from '@/../../content/changelog/auto-log.json';

// ============================================================================
// Technical Changelog Page - Developer Release Notes
// ============================================================================
// What: Shows commit history organized by category for developers.
// Why: Tech users need quick access to what changed, when, and how many files.
// How: Reads from auto-log.json generated by the Claude hook on each commit.

interface CommitEntry {
  hash: string;
  date: string;
  time: string;
  author: string;
  message: string;
  category: string;
  filesChanged: number;
}

// Category configuration
const CATEGORIES = [
  { key: 'all', label: 'All Changes', icon: '📋' },
  { key: 'Features', label: 'Features', icon: '✨' },
  { key: 'Fixes', label: 'Bug Fixes', icon: '🐛' },
  { key: 'Refactoring', label: 'Refactoring', icon: '🔄' },
  { key: 'Documentation', label: 'Documentation', icon: '📝' },
  { key: 'Configuration', label: 'Configuration', icon: '⚙️' },
  { key: 'Other', label: 'Other', icon: '📦' },
];

// Parse commit message prefix to extract type
function getCommitType(message: string): string {
  const prefixes: Record<string, string> = {
    'Add:': 'Features',
    'Fix:': 'Fixes',
    'Refactor:': 'Refactoring',
    'Docs:': 'Documentation',
    'Config:': 'Configuration',
    'Test:': 'Testing',
    'Remove:': 'Refactoring',
  };

  for (const [prefix, type] of Object.entries(prefixes)) {
    if (message.startsWith(prefix)) {
      return type;
    }
  }

  return 'Other';
}

export default function TechnicalChangelogPage() {
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');

  // Parse and enhance commit data
  const commits: CommitEntry[] = useMemo(() => {
    return (changelogData as CommitEntry[]).map((entry) => ({
      ...entry,
      category: entry.category || getCommitType(entry.message),
    }));
  }, []);

  // Filter commits
  const filteredCommits = useMemo(() => {
    return commits.filter((commit) => {
      const matchesCategory = selectedCategory === 'all' || commit.category === selectedCategory;
      const matchesSearch = searchQuery === '' ||
        commit.message.toLowerCase().includes(searchQuery.toLowerCase()) ||
        commit.hash.toLowerCase().includes(searchQuery.toLowerCase());
      return matchesCategory && matchesSearch;
    });
  }, [commits, selectedCategory, searchQuery]);

  // Group commits by category for stats
  const categoryStats = useMemo(() => {
    const stats: Record<string, number> = { all: commits.length };
    commits.forEach((commit) => {
      stats[commit.category] = (stats[commit.category] || 0) + 1;
    });
    return stats;
  }, [commits]);

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 md:px-8 py-8">
      <PageHeader
        title="Technical Changelog"
        description="Complete commit history and release notes for developers."
      />

      {/* Summary Stats */}
      <section className="mb-8">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <Card hoverColor="purple" hoverEffect="lift" className="text-center">
            <div className="text-3xl font-bold text-purple-600 dark:text-purple-400">
              {commits.length}
            </div>
            <div className={`text-sm ${formInputColors.helper}`}>Total Commits</div>
          </Card>
          <Card hoverColor="green" hoverEffect="lift" className="text-center">
            <div className="text-3xl font-bold text-green-600 dark:text-green-400">
              {categoryStats['Features'] || 0}
            </div>
            <div className={`text-sm ${formInputColors.helper}`}>Features Added</div>
          </Card>
          <Card hoverColor="blue" hoverEffect="lift" className="text-center">
            <div className="text-3xl font-bold text-blue-600 dark:text-blue-400">
              {categoryStats['Fixes'] || 0}
            </div>
            <div className={`text-sm ${formInputColors.helper}`}>Bugs Fixed</div>
          </Card>
          <Card hoverColor="gold" hoverEffect="lift" className="text-center">
            <div className="text-3xl font-bold text-gold-600 dark:text-gold-400">
              {commits.reduce((sum, c) => sum + c.filesChanged, 0)}
            </div>
            <div className={`text-sm ${formInputColors.helper}`}>Files Changed</div>
          </Card>
        </div>
      </section>

      {/* Filters */}
      <section className="mb-8">
        <Card hoverColor="gray" hoverEffect="none">
          <div className="flex flex-col md:flex-row gap-4">
            {/* Search */}
            <div className="flex-1">
              <label htmlFor="search" className="sr-only">Search commits</label>
              <input
                id="search"
                type="text"
                placeholder="Search commits by message or hash..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full px-4 py-2 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100"
              />
            </div>

            {/* Category filter */}
            <div className="flex flex-wrap gap-2">
              {CATEGORIES.map((cat) => (
                <button
                  key={cat.key}
                  onClick={() => setSelectedCategory(cat.key)}
                  className={`px-3 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-1.5 ${
                    selectedCategory === cat.key
                      ? 'bg-purple-600 text-white'
                      : 'bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
                  }`}
                >
                  <span aria-hidden="true">{cat.icon}</span>
                  <span>{cat.label}</span>
                  {categoryStats[cat.key] !== undefined && (
                    <span className={`ml-1 text-xs ${
                      selectedCategory === cat.key ? 'text-purple-200' : 'text-gray-500'
                    }`}>
                      ({categoryStats[cat.key]})
                    </span>
                  )}
                </button>
              ))}
            </div>
          </div>
        </Card>
      </section>

      {/* Commit List */}
      <section>
        <h2 className={`text-lg font-semibold ${headingColors.primary} mb-4`}>
          {selectedCategory === 'all' ? 'All Commits' : `${selectedCategory} Commits`}
          <span className={`ml-2 text-sm font-normal ${formInputColors.helper}`}>
            ({filteredCommits.length} results)
          </span>
        </h2>

        {filteredCommits.length === 0 ? (
          <Card hoverColor="gray" hoverEffect="none" className="text-center py-12">
            <div className="text-4xl mb-4" aria-hidden="true">🔍</div>
            <h3 className={`font-medium ${headingColors.secondary}`}>No commits found</h3>
            <p className={formInputColors.helper}>
              Try adjusting your search or category filter.
            </p>
          </Card>
        ) : (
          <div className="space-y-3">
            {filteredCommits.map((commit, index) => (
              <CommitCard key={`${commit.hash}-${index}`} commit={commit} />
            ))}
          </div>
        )}
      </section>

      {/* API Changes Notice */}
      <section className="mt-12">
        <Card hoverColor="blue" hoverEffect="none">
          <div className="flex items-start gap-4">
            <div className="text-3xl" aria-hidden="true">📡</div>
            <div>
              <h3 className={`font-semibold ${headingColors.secondary} mb-2`}>
                API Changes
              </h3>
              <p className={formInputColors.helper}>
                Breaking API changes are documented in commit messages with the &quot;BREAKING:&quot; prefix.
                Filter by &quot;Features&quot; or search for &quot;API&quot; to find endpoint changes.
              </p>
              <p className={`mt-2 ${formInputColors.helper}`}>
                For detailed API documentation, see the{' '}
                <a href="/guide" className="text-blue-600 dark:text-blue-400 underline">
                  Developer Guide
                </a>.
              </p>
            </div>
          </div>
        </Card>
      </section>
    </div>
  );
}

// ============================================================================
// Commit Card Component
// ============================================================================

function CommitCard({ commit }: { commit: CommitEntry }) {
  const categoryColors: Record<string, string> = {
    Features: 'bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-300',
    Fixes: 'bg-red-100 dark:bg-red-900/30 text-red-800 dark:text-red-300',
    Refactoring: 'bg-purple-100 dark:bg-purple-900/30 text-purple-800 dark:text-purple-300',
    Documentation: 'bg-blue-100 dark:bg-blue-900/30 text-blue-800 dark:text-blue-300',
    Configuration: 'bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-gray-300',
    Other: 'bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-gray-300',
    Testing: 'bg-yellow-100 dark:bg-yellow-900/30 text-yellow-800 dark:text-yellow-300',
  };

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-4 hover:border-purple-300 dark:hover:border-purple-600 transition-colors">
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1 min-w-0">
          {/* Commit message */}
          <p className={`font-medium ${headingColors.primary} mb-2`}>
            {commit.message}
          </p>

          {/* Meta info */}
          <div className="flex flex-wrap items-center gap-3 text-sm">
            {/* Category badge */}
            <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
              categoryColors[commit.category] || categoryColors.Other
            }`}>
              {commit.category}
            </span>

            {/* Hash */}
            <code className="px-2 py-0.5 bg-gray-100 dark:bg-gray-700 rounded text-gray-600 dark:text-gray-400 font-mono text-xs">
              {commit.hash}
            </code>

            {/* Author */}
            <span className={formInputColors.helper}>
              by {commit.author}
            </span>

            {/* Files changed */}
            <span className={formInputColors.helper}>
              {commit.filesChanged} file{commit.filesChanged !== 1 ? 's' : ''} changed
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
